version: '3.1'

volumes:
  mongo-volume:
  rmq-volume:
  neo-volume:
  influx-volume:
  prometheus-volume:
  grafana-volume:
  servicecontrol-volume:

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-volume:/data/db
    ports:
      - 27017:27017 

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 7001:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    volumes:
      - rmq-volume:/var/lib/rabbitmq
    ports:
      - 7002:15672
      - 5672:5672

  neo4j:
    image: neo4j
    restart: always
    volumes:
      - neo-volume:/data
    ports:
      - 7003:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none

  influxdb:
    image: influxdb:1.8
    restart: always
    volumes:
      - influx-volume:/var/lib/influxdb
    ports:
      - 8086:8086

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - prometheus-volume:/data
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana-oss
    restart: always
    volumes:
      - grafana-volume:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 7004:3000
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

