{
 "title": "Sys memory - BaseApi",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "System virtual memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "system_virtual_memory{app=\"BaseApi\"}/1000000000",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "System memory working set",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "system_memory_working_set{app=\"BaseApi\"}/1000000000",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "System user cpu percentage used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "system_user_cpu_percentage_used{app=\"BaseApi\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "System non paged memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "system_non_paged_system_memory{app=\"BaseApi\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "System total cpu percentage used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "system_total_cpu_percentage_used{app=\"BaseApi\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "System private memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "system_private_memory{app=\"BaseApi\"}/1000000000",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}